### ISSUE TITLE
에러가 발생하는데 확인 좀 부탁드려요

### ISSUE THREAD

**Issue by mostechlee** [white-HAK/Auto-Selfchaek#5]
Traceback (most recent call last):
  File "csd2.py", line 161, in <module>
    print(selfcheck("이름","090515","부산","금빛","초"))
  File "csd2.py", line 147, in selfcheck
    userPNo = response.json()[0]['userPNo']
  File "/usr/lib/python3/dist-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by white-HAK** [comment]
이름을 맞게 입력해도 같은 증상인가요?

**Comment by mostechlee** [comment]
네 이름을 맞게 입력했는데도 같은 증상입니다.

**Comment by white-HAK** [comment]
비밀번호가 필요하도록 사이트가 변경 되었네용~~

**Comment by white-HAK** [comment]
수정 완료!!
